### ISSUE TITLE
Observed inconsistencies with geo-specific responses with resolver IP vs ECS

### ISSUE THREAD

**Issue by rjb-sophos** [facebook/dns#77]
We run a network of DNS resolvers, running on AWS infrastructure. We have observed issues with all Meta domains such as facebook.com, instagram.com, whatsapp.com etc. where the IP address returned in response to a query with no ECS data appears to be in the incorrect region. When querying the with the IP address of the resolver in an ECS field, we get a geo-appropriate response.

Investigations so far have shown that the issue seems very much tied to the IP address of the resolver - switching IP addresses and repeating the queries can result in different responses. It has also shown that the responses for a given IP are consistent over time, although they do change occasionally. For example, an IP address located in Mumbai that on Friday was consistently receiving Singapore-based IP addresses for star-mini.c10r.facebook.com was, when tested again on Monday, receiving a Seattle-based IP address in response to the same query. Obviously, neither is ideal. At any given time, the same response is received from all four NS instances for facebook.com (a.ns.facebook.com through d.ns.facebook.com).

It's not clear if this is an issue with the code or with data. I notice from looking through the code that when an ECS field is present in a request, an attempt is first made to resolve for that Subnet, and that the resolver IP is only used if that is not present or fails. I also noticed that the lookup for the Resolver IP may select a different location map than an ECS query for the same name. Apologies if this is not the correct forum to raise this issue, but if you can point me at the right place I'd be very grateful.

The impact of this issue right now is that customers using our resolvers are seeing traffic to Meta services directed from India to Singapore or even Seattle, which in some cases impacts peering arrangements and thus incurs significant costs for them, in addition to the performance issues.

**Comment by deathowl** [comment]
Hi, I've received your email and i forwarded the question to the broader internal DNS team .
Recommendation by our targeting-focused members is to enable ECS on your resolvers.

**Comment by rjb-sophos** [comment]
Thanks for the response and for forwarding on the enquiry. We are investigating implementation of ECS although this isn’t seen universally as a Good Thing.

I’m happy to engage as necessary to provide more detail on our observations.


From: Csergő Bálint ***@***.***>
Date: Wednesday, September 11, 2024 at 10:09
To: facebook/dns ***@***.***>
Cc: Richard Baldry ***@***.***>, Author ***@***.***>
Subject: Re: [facebook/dns] Observed inconsistencies with geo-specific responses with resolver IP vs ECS (Issue #77)


Hi, I've received your email and i forwarded the question to the broader internal DNS team .
Recommendation by our targeting-focused members is to enable ECS on your resolvers.
